### ISSUE TITLE
Give route higher preference over method

### ISSUE THREAD

**Issue by ulrikstrid** [hapijs/call#12]
I think the actual route should be the primary decider on if the route is more specific rather then the method. As an example, in a project I'm working on we have a proxy route that is prefixed with /api/ and should be accessible with any method.

```
server.route({
    method: '*',
    path: '/api/{param*}',
    handler: {
        proxy: {
            mapUri: uriMapper,
            passThrough: true
        }
    }
});
```

I want that route to be more specific than our route that serves files:

```
server.route({
    method: 'GET',
    path: '/{param*}',
    handler: function (request, reply) {

        reply.file(Path.resolve('build') + '/index.html');
    }
});
```

But currently we have to loop through a list of methods and create the api-routes.

**Comment by ulrikaugustsson** [comment]
Is this something that will happen or should we close this?

**Comment by hueniverse** [comment]
The request makes sense but there is no easy way to implement it without significant changes to how the current router works. I keep these things open in case a refactor in the future can accommodate.
