### ISSUE TITLE
Multiple params in the same segment

### ISSUE THREAD

**Issue by mtharrison** [hapijs/call#22]
```js
/download/{filename}.{ext}
```

Call seems to support the above style, [it looks like there's even tests for it](https://github.com/hapijs/call/blob/master/test/regex.js#L74). The [Routing Tutorial on hapijs.com](http://hapijs.com/tutorials/routing) says this won't work:

> you may only have one named parameter per segment. That means that /{filename}.jpg is valid while /{filename}.{ext} is not.

So is this an out of date tutorial of an undocumented feature that shouldn't be relied upon?

**Comment by hueniverse** [comment]
The docs are out dated. It is slower than single param per segment though.

**Comment by mtharrison** [comment]
Thanks, I'll PR the tutorial.
