### ISSUE TITLE
No "Path Segment Normalization"?

### ISSUE THREAD

**Issue by kanongil** [hapijs/call#28]
How come [Case Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2.1) and [Percent-Encoding Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2.2) from [RFC3986](https://tools.ietf.org/html/rfc3986) are applied to paths in [Router#normalize()](https://github.com/hapijs/call/blob/c346cd4f1091643c00085bcea0b876d524ef3713/lib/index.js#L156-L176), but [Path Segment Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2.3) is omitted?

**Comment by hueniverse** [comment]
Cause no one cared about this until now?

**Comment by kanongil** [comment]
I could probably do a PR for this if you think it is likely to get merged. It should make hapi safer by never including "./" and "../" path segments in the routing.

Note that normalization can change the matched route when such relative paths are used. As far as I know, it should not be an issue in browsers, which applies the normalization to outbound requests.

It is also somewhat unlikely that it affect any other clients negatively, but it will be a breaking change (unless it's a non-default option).

**Comment by hueniverse** [comment]
So the idea is to turn `/a/./../b` into `/b`?

**Comment by kanongil** [comment]
Pretty much, yes.

As I said, browsers already do it before sending a request, so no change in behavior there. Even modern versions of curl does it (see https://daniel.haxx.se/blog/2013/07/30/dotdot-removal-in-libcurl/). Makes sense to do it at the server level as well, removing potential attack vectors.

**Comment by kanongil** [comment]
Actually, I think the current behavior could be considered a bug.

If I interpret the RFC correctly, requests for `http://server/a` should in fact always generate the exact same response as `http://server/b/../a`.

**Comment by hueniverse** [comment]
I'll take a PR.
