### ISSUE TITLE
Paths Matched Literally Have Different Params than Paths Matched with Mixed Nodes/Edges

### ISSUE THREAD

**Issue by Tornquist** [hapijs/call#35]
I have three paths:

`/path_1`
`/path_1{extension?}`
`/path_2{extension?}`

Within all of these paths, I have validation using joi set up as such:

* `extension: joi.string().regex(/\.(csv)$/)` (path_2)
* `extension: joi.string().valid('.pdf')`. (path_1)

From working through the code here in `call`, I can see that one of the three paths is matched as a direct string literal (the one that is an exact string literal). The other two are matched after being split into parts, and the individual parts are matched.

Both receipt paths send to the same handler, so `extension` is either set, or it is `null`. For `sales/report`, extension is always set, because the way the path is split up requires it, even if a value is not required. Without adding `allow('')` to the joi specification, it's rejected, because an empty string does not match without being explicitly allowed. (As is clearly defined in the hapi docs)

I guess my question is **what is the expected behavior/design?** and **why are the trailing ends of trees handled as empty strings instead of null?**

Replacing line 262 of *segment.js* with:

```
let cleanArray = result.array.filter((a) => a.length > 0 )
return { record: result.record, array: array.concat(cleanArray) };
```

seems to resolve the issue for me, but I'm sure there are side effects of that action.

Is the recommended pattern for optional extensions:

1. `/path_1` and `/path_1{extension?}` with validation as `extension: joi.string().valid('.pdf')`
2. `/path_2{extension?}` with validation as `extension: joi.string().allow('').valid('.csv')`

Option #2 is nice, because it's a single line, but then extension has to be manually handled as an empty string or the valid string. It's not passed in as null, as you may expect when a string is not required.

**Comment by Tornquist** [comment]
What I find most concerning/confusing about the current behavior is that strings default to an empty string, but other types such as numbers stay null.

**Comment by hueniverse** [comment]
Can you submit a PR that shows the issue you are having?

**Comment by hueniverse** [comment]
No response.
